#!/usr/bin/env python3
"""Run generated-fixture regressions against the real CLI and product probe."""
import argparse
import collections
import hashlib
import json
import os
import pathlib
import subprocess
import sys
import tempfile
import time
import traceback

# Keep generated bytecode out of the source tree as well as generated images.
sys.dont_write_bytecode = True
from fixtures import (COLLISIONS, DIRS, EXT2_DIRS, EXT2_FILES, EXT2_LINKS, FAT_FILES,
                      FILES, INTERLEAVED_FILES, INTERLEAVED_DIRS, MTIME, SIGNAL_FILES, generate)


from filemap import default_mapping, external_mapping, generate_mapping, mapping_errors
from sysv import generate_sysv, check_sysv
from xenix import generate_xenix, check_xenix
from eafs import generate_eafs, check_eafs
from okr import generate_okr, check_okr


class Skipped(Exception):
    pass


def require(condition, message):
    # Do not use assert: python -O must still enforce every check.
    if not condition:
        raise RuntimeError(message)


def digest(data):
    return hashlib.sha256(data).hexdigest()


def tree(path):
    files, dirs = {}, set()
    for item in path.rglob("*"):
        name = item.relative_to(path).as_posix()
        require(not item.is_symlink(), f"unexpected output symlink: {item}")
        if item.is_dir():
            dirs.add(name)
        else:
            data = item.read_bytes()
            files[name] = (len(data), digest(data))
    return files, dirs


def check_tree(path, files, dirs=()):
    actual_files, actual_dirs = tree(path)
    expected = {name: (len(data), digest(data)) for name, data in files.items()}
    require(actual_files == expected, f"file inventory/size/hash mismatch: {path}\n{actual_files}\n{expected}")
    require(actual_dirs == set(dirs), f"directory inventory mismatch: {actual_dirs} != {set(dirs)}")


class Suite:
    def __init__(self, cli, probe, root, filemap_fixtures=None):
        self.cli, self.probe, self.root = cli, probe, root
        self.filemap_fixtures = filemap_fixtures
        self.fixtures = root / "fixtures"
        self.results, self.commands = [], []

    def command(self, argv, expected=0, preexec_fn=None):
        started = time.monotonic()
        result = subprocess.run([str(a) for a in argv], capture_output=True,
                                text=True, encoding="utf-8", errors="replace", timeout=60,
                                preexec_fn=preexec_fn)
        self.commands.append({"argv": [str(a) for a in argv], "exit": result.returncode,
                              "stdout": result.stdout, "stderr": result.stderr,
                              "seconds": time.monotonic() - started})
        require(result.returncode == expected,
                f"exit {result.returncode}, expected {expected}: {argv}\n{result.stdout}\n{result.stderr}")
        if expected:
            require(bool(result.stderr.strip()), f"failure without diagnostic: {argv}")
        return result

    def cli_run(self, image, *args, expected=0):
        return self.command([self.cli, "-f", self.fixtures / image, *args], expected)

    def extract(self, image, output, sources, *extra, expected=0):
        args = ["-o", self.root / output, *extra]
        for source in sources:
            args += ["-e", "(img0)/" + source]
        return self.cli_run(image, *args, expected=expected)

    def case(self, name, function):
        try:
            function()
            status = "PASS"
            self.results.append({"name": name, "status": status})
            print(status, name, flush=True)
        except Skipped as reason:
            self.results.append({"name": name, "status": "SKIP", "reason": str(reason)})
            print("SKIP", name, reason, flush=True)
        except Exception:
            error = traceback.format_exc()
            self.results.append({"name": name, "status": "FAIL", "error": error})
            print("FAIL", name, error, flush=True)

    def basic(self, image, files, dirs, links=()):
        listing = self.cli_run(image, "--list=(img0)/")
        expected = {name for name in files if "/" not in name}
        expected |= {name + "/" for name in dirs if "/" not in name}
        expected |= set(links)
        require(collections.Counter(listing.stdout.splitlines()) == collections.Counter(expected),
                f"root listing mismatch: {listing.stdout!r}")
        for directory in dirs:
            listing = self.cli_run(image, "--list=(img0)/" + directory)
            prefix = directory + "/"
            children = {name[len(prefix):] for name in files
                        if name.startswith(prefix) and "/" not in name[len(prefix):]}
            children |= {name[len(prefix):] + "/" for name in dirs
                         if name.startswith(prefix) and "/" not in name[len(prefix):]}
            require(collections.Counter(listing.stdout.splitlines()) == collections.Counter(children),
                    "child listing mismatch")
        self.extract(image, image, [""])
        check_tree(self.root / image / "img0", files, dirs)

    def existing(self):
        target = self.root / "existing"
        target.mkdir()
        (target / "hello.txt").write_bytes(b"user-owned sentinel")
        (target / "nested").mkdir()
        (target / "nested" / "keep.txt").write_bytes(b"keep directory")
        self.extract("basic.tar", "existing", ["hello.txt", "hello.txt", "nested"])
        check_tree(target, {"hello.txt": b"user-owned sentinel",
                            "hello (1).txt": FILES["hello.txt"],
                            "hello (2).txt": FILES["hello.txt"],
                            "nested/keep.txt": b"keep directory",
                            "nested (1)/data.bin": FILES["nested/data.bin"]},
                   {"nested", "nested (1)"})

    def type_collisions(self):
        target = self.root / "type-collisions"
        target.mkdir()
        (target / "hello.txt").mkdir()
        (target / "hello.txt" / "keep").write_bytes(b"keep")
        (target / "nested").write_bytes(b"keep file")
        self.extract("basic.tar", "type-collisions", ["hello.txt", "nested"])
        check_tree(target, {"hello.txt/keep": b"keep", "nested": b"keep file",
                            "hello (1).txt": FILES["hello.txt"],
                            "nested (1)/data.bin": FILES["nested/data.bin"]},
                   {"hello.txt", "nested (1)"})

    def names(self):
        self.extract("collisions.tar", "names", [""])
        path = self.root / "names" / "img0"
        actual, dirs = tree(path)
        require(not dirs and len(actual) == len(COLLISIONS), "collision lost a file")
        require(collections.Counter(actual.values()) == collections.Counter(
            (len(data), digest(data)) for data in COLLISIONS.values()), "collision overwrote content")
        if os.name == "nt":
            names = list(actual)
            require(len({n.casefold() for n in names}) == len(names), "case collision unresolved")
            require(all(not any(c in n for c in '<>:"/\\|?*') for n in names), "invalid host name")
            require("CON_.txt" in names and "trailing_" in names, "reserved/trailing name not sanitized")
        else:
            probe = self.root / "case-probe"
            probe.write_bytes(b"x")
            case_sensitive = not (self.root / "CASE-PROBE").exists()
            probe.unlink()
            expected = dict(COLLISIONS)
            if not case_sensitive:
                expected["same (1).txt"] = expected.pop("same.txt")
            check_tree(path, expected)

    def partial_failure(self):
        # Explicit source order proves that the good file runs AFTER read failure.
        result = self.extract("broken.img", "partial", ["bad.bin", "hello.txt"], expected=1)
        require("failed 1 file(s)" in result.stderr and "Extracted 1 file(s), 840 bytes" in result.stderr,
                f"partial failure summary wrong: {result.stderr}")
        check_tree(self.root / "partial", {"hello.txt": FAT_FILES["hello.txt"]})

    def times(self):
        sources = ["hello.txt", "nested", "empty-dir"]
        for image, files, dirs in [("basic.tar", FILES, DIRS), ("basic.ext2", EXT2_FILES, EXT2_DIRS)]:
            before = time.time()
            self.extract(image, f"times-{image}", sources)
            self.extract(image, f"no-times-{image}", sources, "--no-times")
            after = time.time()
            for option, output in (("", f"times-{image}"), ("--no-times", f"no-times-{image}")):
                wanted = {name for source in sources for name in files
                          if name == source or name.startswith(source + "/")}
                check_tree(self.root / output, {k: v for k, v in files.items() if k in wanted}, dirs)
                for name in ("hello.txt", "nested", "nested/data.bin", "empty-dir"):
                    stamp = (self.root / output / name).stat().st_mtime
                    require(abs(stamp - MTIME) <= 2 if not option else before - 2 <= stamp <= after + 2,
                            f"timestamp mismatch: {output}/{name}: {stamp}")

    def links(self):
        result = self.extract("links.tar", "links", [""])
        require("skipped 1 symlink(s)" in result.stderr, "symlink skip missing from summary")
        check_tree(self.root / "links" / "img0", {"hello.txt": FILES["hello.txt"]})
        result = self.extract("basic.ext2", "ext2-links", [""])
        require("skipped 2 symlink(s)" in result.stderr,
                f"ext2 symlink skip missing from summary: {result.stderr}")
        check_tree(self.root / "ext2-links" / "img0", EXT2_FILES, EXT2_DIRS)

    def loops(self):
        image = self.fixtures / "loop.tar"
        listing = self.command([self.cli, "-f", image, "-p", "(img0)/mid.tar", "--list=(loop0)/"])
        require(collections.Counter(listing.stdout.splitlines()) == collections.Counter(["deep.tar", "mid.txt"]),
                f"loop0 listing mismatch: {listing.stdout!r}")
        listing = self.command([self.cli, "-f", image, "-p", "(img0)/mid.tar",
                                "-p", "(loop0)/deep.tar", "--list=(loop1)/"])
        require(listing.stdout.splitlines() == ["deep.txt"],
                f"nested loop listing mismatch: {listing.stdout!r}")
        listing = self.command([self.cli, "-f", image, "--loop-dec=(img0)/mid.tar.gz", "--list=(loop0)/"])
        require(collections.Counter(listing.stdout.splitlines()) == collections.Counter(["deep.tar", "mid.txt"]),
                f"loop-dec listing mismatch: {listing.stdout!r}")
        compressed = self.command([self.cli, "-d", self.fixtures / "basic.img.gz", "--list=(img0)/"])
        require(collections.Counter(compressed.stdout.splitlines()) == collections.Counter(
            ["hello.txt", "empty.bin", "dir/"]), f"file-dec listing mismatch: {compressed.stdout!r}")
        devices = self.command([self.cli, "-f", image, "-f", self.fixtures / "basic.tar",
                                "-p", "(img0)/mid.tar", "-p", "(img0)/mid.tar", "--list"])
        require(all(token in devices.stdout for token in ("(img0)", "(img1)", "(loop0)", "(loop1)")),
                f"loop counters/order changed: {devices.stdout!r}")
        out = self.root / "loops"
        self.command([self.cli, "-f", image, "-p", "(img0)/mid.tar", "-p", "(loop0)/deep.tar",
                      "-e", "(loop1)/deep.txt", "-o", out])
        require((out / "deep.txt").read_bytes() == b"deep tar payload\n", "nested loop extraction mismatch")
        self.command([self.cli, "-p", "(img0)/mid.tar", "-f", image, "--list"], expected=1)
        self.command([self.cli, "-f", image, "--loop-dec=(img0)/mid.tar.gz",
                      "-p", "(img0)/mid.tar.gz", "--list=(loop1)/"], expected=1)
        self.command([self.cli, "-f", image, "--loop-dec=(img0)/bad.gz", "--list=(loop0)/"], expected=1)
        self.command([self.cli, "--loop"], expected=2)
        self.command([self.cli, "--loop-dec"], expected=2)

    def symlink_destination(self):
        if os.name == "nt":
            raise Skipped("dangling-symlink destination semantics are POSIX-only")
        target = self.root / "symlink-destination"
        target.mkdir()
        try:
            os.symlink("missing-target", target / "hello.txt")
        except (OSError, NotImplementedError) as error:
            raise Skipped(f"host cannot create symlinks: {error}")
        self.extract("basic.tar", "symlink-destination", ["hello.txt"])
        require((target / "hello.txt").is_symlink(), "existing destination symlink was replaced")
        require((target / "hello (1).txt").read_bytes() == FILES["hello.txt"],
                "extraction did not reserve a fresh name beside the symlink")

    def directory_reservation(self):
        target = self.root / "directory-reservation"
        (target / "hello.txt").mkdir(parents=True)
        (target / "hello (1).txt").mkdir()
        self.extract("basic.tar", "directory-reservation", ["hello.txt"])
        require((target / "hello.txt").is_dir() and (target / "hello (1).txt").is_dir(),
                "existing destination directories were replaced")
        require((target / "hello (2).txt").read_bytes() == FILES["hello.txt"],
                "existing directories did not reserve the file name")

    def truncated(self):
        truncated = self.root / "truncated.img"
        truncated.write_bytes((self.fixtures / "basic.img").read_bytes()[:4096])
        out = self.root / "truncated-output"
        self.command([self.cli, "-f", truncated, "--list=(img0)/"], expected=1)
        self.command([self.cli, "-f", truncated, "-e", "(img0)/hello.txt", "-o", out], expected=1)
        require(not (out / "hello.txt").exists(), "truncated source left a completed output file")

    def limited_write(self):
        if os.name == "nt":
            raise Skipped("RLIMIT_FSIZE is POSIX-only")
        import resource
        import signal

        def limit():
            resource.setrlimit(resource.RLIMIT_FSIZE, (1024, 1024))
            signal.signal(signal.SIGXFSZ, signal.SIG_IGN)

        out = self.root / "limited-write"
        result = self.command([self.cli, "-f", self.fixtures / "basic.tar",
                               "-e", "(img0)/nested/data.bin", "-e", "(img0)/hello.txt",
                               "-o", out], expected=1, preexec_fn=limit)
        require("failed 1 file(s)" in result.stderr, f"write failure summary missing: {result.stderr}")
        require(not (out / "data.bin").exists(), "failed output file retained")
        require((out / "hello.txt").read_bytes() == FILES["hello.txt"],
                "later source lost after the write failure")

    def signal_cancellation(self):
        if os.name == "nt":
            raise Skipped("OS signal cancellation is POSIX-only")
        import signal

        out = self.root / "signal"
        process = subprocess.Popen([str(self.cli), "-f", str(self.fixtures / "signal.tar"),
                                    "-e", "(img0)/", "-o", str(out)],
                                   stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                                   text=True, encoding="utf-8", errors="replace")
        try:
            for line in process.stderr:
                if line.startswith("Extracted ["):
                    process.send_signal(signal.SIGINT)
                    break
            stderr = process.stderr.read()
            code = process.wait(timeout=60)
        finally:
            if process.poll() is None:
                process.kill()
                process.wait()
        require(code == 1, f"signal cancellation exit {code}:\n{stderr}")
        require("extraction cancelled" in stderr, f"cancellation diagnostic missing:\n{stderr}")
        files, dirs = tree(out / "img0")
        require(not dirs, f"unexpected cancellation directories: {dirs}")
        expected = {name: (len(data), digest(data)) for name, data in SIGNAL_FILES.items()}
        require(0 < len(files) < len(expected), f"signal did not interrupt extraction: {len(files)}")
        require(all(files[name] == expected[name] for name in files),
                "cancelled extraction retained a partial or corrupted file")

    def errors(self):
        self.command([self.cli, "--help"])
        self.command([self.cli, "--not-an-option"], expected=2)
        self.cli_run("unknown.img", "--list=(img0)/", expected=1)
        self.cli_run("basic.tar", "--list=(img0)/missing", expected=1)
        target = self.root / "blocked-output"
        target.write_bytes(b"user-owned output file")
        self.extract("basic.tar", "blocked-output", ["hello.txt"], expected=1)
        require(target.read_bytes() == b"user-owned output file", "invalid output damaged existing file")

    def run(self):
        generate(self.fixtures)
        generate_mapping(self.fixtures)
        generate_sysv(self.fixtures)
        generate_xenix(self.fixtures)
        generate_eafs(self.fixtures)
        generate_okr(self.fixtures)
        before = {p.name: digest(p.read_bytes()) for p in self.fixtures.iterdir()}
        self.case("zip list/extract", lambda: self.basic("basic.zip", FILES, DIRS))
        self.case("tar list/extract", lambda: self.basic("basic.tar", FILES, DIRS))
        self.case("fat12 list/extract", lambda: self.basic("basic.img", FAT_FILES, {"dir"}))
        self.case("ext2 list/extract", lambda: self.basic("basic.ext2", EXT2_FILES, EXT2_DIRS, EXT2_LINKS))
        for name, function in [("existing destinations and repeated sources", self.existing),
                               ("file/directory collisions", self.type_collisions),
                               ("host filename collisions", self.names),
                               ("existing destination symlink", self.symlink_destination),
                               ("directories reserve file names", self.directory_reservation),
                               ("partial read failure and rollback", self.partial_failure),
                               ("truncated image failure", self.truncated),
                               ("write failure rollback", self.limited_write),
                               ("file/directory timestamps", self.times),
                               ("symlink skip", self.links),
                               ("loopback mounts and decompression", self.loops),
                               ("CLI errors", self.errors)]:
            self.case(name, function)
        self.case("metadata mapping, range/stop/read and corruption", lambda: default_mapping(self))
        self.case("System V/Xenix/V7/Coherent list, read and corruption", lambda: check_sysv(self))
        self.case("Xenix divisions, geometry, nested extraction and corruption", lambda: check_xenix(self))
        self.case("SCO EAFS/ES51K extended directories and corruption", lambda: check_eafs(self))
        self.case("OKR 810/811 volumes, segments, integrity and corruption", lambda: check_okr(self))
        self.case("mapping CLI errors", lambda: mapping_errors(self))
        if self.filemap_fixtures is not None:
            self.case("external mapping matrix", lambda: external_mapping(self, self.filemap_fixtures))
        self.case("OS signal cancellation", self.signal_cancellation)
        self.case("same-process recovery and cancellation", lambda: self.command(
            [self.probe, self.fixtures, self.root / "probe"]))
        self.case("post-cancel output hash", lambda: check_tree(self.root / "probe" / "recovered",
                                                               {"hello.txt": FAT_FILES["hello.txt"]}))
        self.case("cancellation preserves completed and existing files", lambda: check_tree(
            self.root / "probe" / "cancel", {"hello.txt": FAT_FILES["hello.txt"],
                                               "keep.txt": b"existing destination"}))
        self.case("noncontiguous TAR list/extract", lambda: self.basic("noncontiguous.tar", FILES, DIRS))
        for image in ("interleaved.tar", "implicit.tar"):
            self.case(image + " list/extract", lambda image=image: self.basic(
                image, INTERLEAVED_FILES, INTERLEAVED_DIRS))
        self.case("source images unchanged", lambda: require(
            before == {p.name: digest(p.read_bytes()) for p in self.fixtures.iterdir()}, "source image changed"))
        report = {"cli": str(self.cli), "probe": str(self.probe),
                  "cli_sha256": digest(self.cli.read_bytes()), "probe_sha256": digest(self.probe.read_bytes()),
                  "fixtures_sha256": before,
                  "results": self.results, "commands": self.commands}
        (self.root / "results.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
        print("Summary:", dict(collections.Counter(r["status"] for r in self.results)), flush=True)
        return int(any(result["status"] == "FAIL" for result in self.results))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cli", required=True, type=pathlib.Path)
    parser.add_argument("--probe", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path,
                        help="Parent for a unique run directory; existing files are never deleted")
    parser.add_argument("--filemap-fixtures", type=pathlib.Path,
                        help="Optional existing full mapping fixture matrix; missing images fail")
    args = parser.parse_args()
    cli, probe = args.cli.resolve(), args.probe.resolve()
    require(cli.is_file() and probe.is_file(), "build both the CLI and product probe first")
    args.output.mkdir(parents=True, exist_ok=True)
    root = pathlib.Path(tempfile.mkdtemp(prefix="run-", dir=args.output.resolve()))
    print(f"Results and generated fixtures: {root}", flush=True)
    return Suite(cli, probe, root, args.filemap_fixtures).run()


if __name__ == "__main__":
    raise SystemExit(main())
